name: Go CI

# Trigger workflow on push or pull request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    # 3. Cache Go modules (optional but speeds up builds)
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # 4. Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # 5. Run tests
    - name: Run tests
      run: go test ./... -v
